/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app.templates.index'
import { Route as AppAuditsIndexRouteImport } from './routes/_app.audits.index'
import { Route as AppTemplatesNewRouteImport } from './routes/_app.templates.new'
import { Route as AppTemplatesIdRouteImport } from './routes/_app.templates.$id'
import { Route as AppAuditsIdRouteImport } from './routes/_app.audits.$id'
import { Route as AppAuditsRunIdRouteImport } from './routes/_app.audits.run.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIndexRoute = AppAuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIdRoute = AppTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIdRoute = AppAuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsRunIdRoute = AppAuditsRunIdRouteImport.update({
  id: '/audits/run/$id',
  path: '/audits/run/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/manager': typeof AppManagerRoute
  '/audits/$id': typeof AppAuditsIdRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/audits/': typeof AppAuditsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/audits/run/$id': typeof AppAuditsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/manager': typeof AppManagerRoute
  '/audits/$id': typeof AppAuditsIdRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/audits': typeof AppAuditsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/audits/run/$id': typeof AppAuditsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/audits/$id': typeof AppAuditsIdRoute
  '/_app/templates/$id': typeof AppTemplatesIdRoute
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/_app/audits/': typeof AppAuditsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/audits/run/$id': typeof AppAuditsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/manager'
    | '/audits/$id'
    | '/templates/$id'
    | '/templates/new'
    | '/audits/'
    | '/templates/'
    | '/audits/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/manager'
    | '/audits/$id'
    | '/templates/$id'
    | '/templates/new'
    | '/audits'
    | '/templates'
    | '/audits/run/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/manager'
    | '/_app/audits/$id'
    | '/_app/templates/$id'
    | '/_app/templates/new'
    | '/_app/audits/'
    | '/_app/templates/'
    | '/_app/audits/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/': {
      id: '/_app/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AppAuditsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$id': {
      id: '/_app/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/$id': {
      id: '/_app/audits/$id'
      path: '/audits/$id'
      fullPath: '/audits/$id'
      preLoaderRoute: typeof AppAuditsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/run/$id': {
      id: '/_app/audits/run/$id'
      path: '/audits/run/$id'
      fullPath: '/audits/run/$id'
      preLoaderRoute: typeof AppAuditsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppManagerRoute: typeof AppManagerRoute
  AppAuditsIdRoute: typeof AppAuditsIdRoute
  AppTemplatesIdRoute: typeof AppTemplatesIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppAuditsIndexRoute: typeof AppAuditsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppAuditsRunIdRoute: typeof AppAuditsRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppManagerRoute: AppManagerRoute,
  AppAuditsIdRoute: AppAuditsIdRoute,
  AppTemplatesIdRoute: AppTemplatesIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppAuditsIndexRoute: AppAuditsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppAuditsRunIdRoute: AppAuditsRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
