/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditsIndexRouteImport } from './routes/_app.audits.index'
import { Route as AppAuditsNewRouteImport } from './routes/_app.audits.new'
import { Route as AppAuditsRecordIdRouteImport } from './routes/_app.audits.record.$id'
import { Route as AppAuditsIdRunRouteImport } from './routes/_app.audits.$id.run'
import { Route as AppAuditsIdEditRouteImport } from './routes/_app.audits.$id.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIndexRoute = AppAuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsNewRoute = AppAuditsNewRouteImport.update({
  id: '/audits/new',
  path: '/audits/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsRecordIdRoute = AppAuditsRecordIdRouteImport.update({
  id: '/audits/record/$id',
  path: '/audits/record/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIdRunRoute = AppAuditsIdRunRouteImport.update({
  id: '/audits/$id/run',
  path: '/audits/$id/run',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsIdEditRoute = AppAuditsIdEditRouteImport.update({
  id: '/audits/$id/edit',
  path: '/audits/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/manager': typeof AppManagerRoute
  '/audits/new': typeof AppAuditsNewRoute
  '/audits/': typeof AppAuditsIndexRoute
  '/audits/$id/edit': typeof AppAuditsIdEditRoute
  '/audits/$id/run': typeof AppAuditsIdRunRoute
  '/audits/record/$id': typeof AppAuditsRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/manager': typeof AppManagerRoute
  '/audits/new': typeof AppAuditsNewRoute
  '/audits': typeof AppAuditsIndexRoute
  '/audits/$id/edit': typeof AppAuditsIdEditRoute
  '/audits/$id/run': typeof AppAuditsIdRunRoute
  '/audits/record/$id': typeof AppAuditsRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/audits/new': typeof AppAuditsNewRoute
  '/_app/audits/': typeof AppAuditsIndexRoute
  '/_app/audits/$id/edit': typeof AppAuditsIdEditRoute
  '/_app/audits/$id/run': typeof AppAuditsIdRunRoute
  '/_app/audits/record/$id': typeof AppAuditsRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/manager'
    | '/audits/new'
    | '/audits/'
    | '/audits/$id/edit'
    | '/audits/$id/run'
    | '/audits/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/manager'
    | '/audits/new'
    | '/audits'
    | '/audits/$id/edit'
    | '/audits/$id/run'
    | '/audits/record/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/manager'
    | '/_app/audits/new'
    | '/_app/audits/'
    | '/_app/audits/$id/edit'
    | '/_app/audits/$id/run'
    | '/_app/audits/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/': {
      id: '/_app/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AppAuditsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/new': {
      id: '/_app/audits/new'
      path: '/audits/new'
      fullPath: '/audits/new'
      preLoaderRoute: typeof AppAuditsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/record/$id': {
      id: '/_app/audits/record/$id'
      path: '/audits/record/$id'
      fullPath: '/audits/record/$id'
      preLoaderRoute: typeof AppAuditsRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/$id/run': {
      id: '/_app/audits/$id/run'
      path: '/audits/$id/run'
      fullPath: '/audits/$id/run'
      preLoaderRoute: typeof AppAuditsIdRunRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits/$id/edit': {
      id: '/_app/audits/$id/edit'
      path: '/audits/$id/edit'
      fullPath: '/audits/$id/edit'
      preLoaderRoute: typeof AppAuditsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppManagerRoute: typeof AppManagerRoute
  AppAuditsNewRoute: typeof AppAuditsNewRoute
  AppAuditsIndexRoute: typeof AppAuditsIndexRoute
  AppAuditsIdEditRoute: typeof AppAuditsIdEditRoute
  AppAuditsIdRunRoute: typeof AppAuditsIdRunRoute
  AppAuditsRecordIdRoute: typeof AppAuditsRecordIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppManagerRoute: AppManagerRoute,
  AppAuditsNewRoute: AppAuditsNewRoute,
  AppAuditsIndexRoute: AppAuditsIndexRoute,
  AppAuditsIdEditRoute: AppAuditsIdEditRoute,
  AppAuditsIdRunRoute: AppAuditsIdRunRoute,
  AppAuditsRecordIdRoute: AppAuditsRecordIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
